### ISSUE TITLE
Dropdown position when the keyboard is shown

### ISSUE THREAD

**Issue by marry1822** [AdelRedaa97/react-native-select-dropdown#151] opened 2023-08-14 10:55 UTC
Hey! I've got a strange behavior: if search is enabled and I open my dropdown, dropdown items jump up when keyboard is shown.
See the attached screenshot:
<img width="562" alt="image" src="https://github.com/AdelRedaa97/react-native-select-dropdown/assets/63728225/ae79f885-a3de-4986-84fa-8e30636bebb3">
Please, help me to fix it.

I expect it to look like this:
<img width="538" alt="image" src="https://github.com/AdelRedaa97/react-native-select-dropdown/assets/63728225/cb4c6173-1677-4d98-a03d-bec537e23658">

**Comment by AdelRedaa97** [comment] 2023-08-14 17:58
The dropdown is implemented using React native's Modal, and it positions the dropdown by calculating the position (X, Y)of the bottom in the screen,  This behavior mey happens because the the dropdown is in a modal and it gets a wrong postion of Y, I will try to fix it this problem, But I want to know if this behavior happens if you put the button outside the Modal?

**Comment by marry1822** [comment] 2023-08-15 02:41
> The dropdown is implemented using React native's Modal, and it positions the dropdown by calculating the position (X, Y)of the bottom in the screen, This behavior mey happens because the the dropdown is in a modal and it gets a wrong postion of Y, I will try to fix it this problem, But I want to know if this behavior happens if you put the button outside the Modal?

It doesn't happen outside of the modal, however, it happens in IOS and Android. 

It would be awesome if you could fix this behavior, because dropdowns are used in modals quite often.
Thanks a lot!

**Comment by AdelRedaa97** [comment] 2023-08-15 13:43
I've tried to put in a Modal and it works fine, I've got a problem with the Android studio so I didn't try it on Android but it works fine on iOS

**Comment by AdelRedaa97** [comment] 2023-08-15 13:55
https://snack.expo.dev/@adelredaa97/rnsd-in-a-modal

Take a look here and tell me if the problem is solved.

**Comment by marry1822** [comment] 2023-08-16 03:59
> https://snack.expo.dev/@adelredaa97/rnsd-in-a-modal
> 
> Take a look here and tell me if the problem is solved.

Not solved.. it jumps up or down on different screen resolutions (different ios devices)
And it happens when search is enabled only.

**Comment by AdelRedaa97** [comment] 2024-03-26 00:02
Fixed in v4.0 take a look at the changes made in v4.0
https://github.com/AdelRedaa97/react-native-select-dropdown?tab=readme-ov-file#-major-changes

Feel free to open the issue again if it still exists

**Closed by AdelRedaa97** 2024-03-26 00:02 UTC
